import QRCode from "qrcode";

/**
 * Builds the diner URL a table's QR code points to:
 *   {APP_URL}/order/{slug}/{tableToken}
 * This is the exact route the diner lands on after scanning (Phase 1).
 */
export function dinerOrderUrl(slug: string, qrToken: string): string {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
  return `${base.replace(/\/$/, "")}/order/${slug}/${qrToken}`;
}

/**
 * The diner URL to encode in a table's QR, preferring the restaurant's branded
 * host when available: verified custom domain → subdomain → platform URL.
 */
export function restaurantOrderUrl(
  r: {
    slug: string;
    subdomain?: string | null;
    customDomain?: string | null;
    customDomainVerified?: boolean;
  },
  qrToken: string,
): string {
  const root = process.env.NEXT_PUBLIC_ROOT_DOMAIN;
  if (r.customDomain && r.customDomainVerified) {
    return `https://${r.customDomain}/t/${qrToken}`;
  }
  if (r.subdomain && root) {
    return `https://${r.subdomain}.${root}/t/${qrToken}`;
  }
  return dinerOrderUrl(r.slug, qrToken);
}

/**
 * Renders a QR code as an inline SVG string. SVG (not PNG) so it stays crisp at
 * any print size. The result is injected via dangerouslySetInnerHTML in the
 * print sheet — safe because the content is generated by us, not user input.
 */
export function qrSvg(data: string): Promise<string> {
  return QRCode.toString(data, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    width: 220,
  });
}
