import Link from "next/link";
import { requireAdminPage } from "@/server/tenancy/require-admin";
import { getTables, getCounterTable, getRestaurantBrief } from "@/server/tables/queries";
import { restaurantOrderUrl, qrSvg } from "@/lib/qr";
import { AddTableForm } from "@/components/admin/AddTableForm";
import { QrDownloadButton } from "@/components/admin/QrDownloadButton";
import { createCounterTable, deleteTable, regenerateQrToken } from "@/server/tables/actions";

export default async function TablesPage() {
  const { restaurantId } = await requireAdminPage();
  const [tables, counter, restaurant] = await Promise.all([
    getTables(restaurantId),
    getCounterTable(restaurantId),
    getRestaurantBrief(restaurantId),
  ]);

  const qrUrl = (qrToken: string) =>
    restaurantOrderUrl(
      {
        slug: restaurant.slug,
        subdomain: restaurant.subdomain,
        customDomain: restaurant.customDomain,
        customDomainVerified: !!restaurant.customDomainVerifiedAt,
      },
      qrToken,
    );

  // Build the diner URL + QR SVG for each table (server-side).
  const rows = await Promise.all(
    tables.map(async (table) => {
      const url = qrUrl(table.qrToken);
      return { table, url, svg: await qrSvg(url) };
    }),
  );

  const counterView = counter
    ? { url: qrUrl(counter.qrToken), svg: await qrSvg(qrUrl(counter.qrToken)) }
    : null;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <Link href="/admin" className="text-sm text-plum-ink/50">
            ← Dashboard
          </Link>
          <h1 className="font-heading text-2xl font-bold">Tables</h1>
          <p className="text-sm text-plum-ink/50">
            Each table has a unique QR that drops the diner straight onto its
            menu.
          </p>
        </div>
        {tables.length > 0 && (
          <Link
            href="/admin/tables/print"
            className="rounded-full px-5 py-2 text-sm font-semibold btn-brand"
          >
            Printable QR sheet →
          </Link>
        )}
      </div>

      <div className="rounded-tile border border-plum-ink/10 bg-white p-4">
        <AddTableForm />
      </div>

      {tables.length === 0 ? (
        <p className="text-sm text-plum-ink/50">
          No tables yet. Add one above, then print its QR.
        </p>
      ) : (
        <ul className="grid gap-3 sm:grid-cols-2">
          {rows.map(({ table, url, svg }) => (
            <li
              key={table.id}
              className="flex items-center gap-4 rounded-tile border border-plum-ink/10 bg-white p-4"
            >
              {/* Inline QR — scan to test, or download/print it */}
              <div
                className="h-28 w-28 shrink-0 rounded-lg border border-plum-ink/10 p-1 [&>svg]:h-full [&>svg]:w-full"
                // Safe: SVG is generated by us from our own data, not user input.
                dangerouslySetInnerHTML={{ __html: svg }}
              />
              <div className="min-w-0 flex-1">
                <span className="font-heading font-bold">Table {table.tableNumber}</span>
                <p className="mt-0.5 truncate text-xs text-plum-ink/40">{url}</p>
                <div className="mt-3 flex flex-wrap items-center gap-2">
                  <QrDownloadButton svg={svg} filename={`table-${table.tableNumber}-qr.svg`} />
                  <form action={regenerateQrToken}>
                    <input type="hidden" name="id" value={table.id} />
                    <button className="rounded-lg border border-plum-ink/15 px-3 py-1.5 text-xs font-semibold">
                      Regenerate QR
                    </button>
                  </form>
                  <form action={deleteTable}>
                    <input type="hidden" name="id" value={table.id} />
                    <button className="text-xs text-muted hover:text-guava">Delete</button>
                  </form>
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}

      {/* Counter / takeout ordering — one QR, customers get an order number. */}
      <div className="rounded-tile border border-plum-ink/10 bg-white p-5">
        <h2 className="font-heading text-lg font-bold">Counter / takeout ordering</h2>
        <p className="mt-1 text-sm text-plum-ink/55">
          For food stalls, carts and takeout: one QR with no tables. Customers scan, order, and
          get an <strong>order number</strong> shown on the Kitchen and Cashier screens. They pay
          at the counter.
        </p>

        {counter && counterView ? (
          <div className="mt-4 flex items-center gap-4 rounded-tile border border-plum-ink/10 p-4">
            <div
              className="h-28 w-28 shrink-0 rounded-lg border border-plum-ink/10 p-1 [&>svg]:h-full [&>svg]:w-full"
              // Safe: SVG is generated by us from our own data, not user input.
              dangerouslySetInnerHTML={{ __html: counterView.svg }}
            />
            <div className="min-w-0 flex-1">
              <span className="font-heading font-bold">🧾 Counter / Takeout</span>
              <p className="mt-0.5 truncate text-xs text-plum-ink/40">{counterView.url}</p>
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <QrDownloadButton svg={counterView.svg} filename="counter-qr.svg" />
                <form action={regenerateQrToken}>
                  <input type="hidden" name="id" value={counter.id} />
                  <button className="rounded-lg border border-plum-ink/15 px-3 py-1.5 text-xs font-semibold">
                    Regenerate QR
                  </button>
                </form>
                <form action={deleteTable}>
                  <input type="hidden" name="id" value={counter.id} />
                  <button className="text-xs text-muted hover:text-guava">Delete</button>
                </form>
              </div>
            </div>
          </div>
        ) : (
          <form action={createCounterTable} className="mt-4">
            <button className="rounded-full px-5 py-2.5 text-sm font-semibold btn-brand">
              Create counter QR
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
